install.packages('ggplot2')
library('ggplot2')
install.packages('lubridate')
library('lubridate')
install.packages('scales')
library('scales')
install.packages('reshape2')
library('reshape2')
install.packages('tm')
library('tm')
install.packages('SnowballC')
library('SnowballC')
install.packages('wordcloud')
library('wordcloud')
install.packages('RColorBrewer')
library('RColorBrewer')
install.packages('stringr')
library('stringr')
install.packages('syuzhet')
library('syuzhet')
install.packages('dplyr')
library('dplyr')
library('corpustools')

data = readLines('/Users/abhi/College Work/Year 3 Semester 2 (Sem 6)/Programming for Data Science Lab/Whatsapp Data/_chat.txt')

docs = Corpus(VectorSource(data))
